-- DELIMITER //
-- CREATE PROCEDURE CreateFarmer(
--     IN farmerName VARCHAR(255),
--     IN farmerEmail VARCHAR(255),
--     IN farmerLocation VARCHAR(255)
-- )
-- BEGIN
--     INSERT INTO farmers (name, email, location)
--     VALUES (farmerName, farmerEmail, farmerLocation);
-- END //
-- DELIMITER ;