-- CREATE PROCEDURE CreateProduct(
--     IN productName VARCHAR(255),
--     IN productPrice DECIMAL(10, 2),
--     IN productFarmerId INT
-- )
-- BEGIN
--     INSERT INTO products (name, price, farmer_id)
--     VALUES (productName, productPrice, productFarmerId);
-- END